name: Auto-Update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
 contents: write

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-jobs.outputs.versions }}
    steps:
      - uses: actions/checkout@v2
      - id: generate-jobs
        name: Generate Jobs
        run: |
          versions="$(jq -c 'keys_unsorted' versions.json)"
          jq . <<<"$versions" # sanity check / debugging aid
          echo "::set-output name=versions::$versions"

  test:
    needs: generate-jobs
    strategy:
      matrix:
        version: ${{ fromJson(needs.generate-jobs.outputs.versions) }}
      fail-fast: false
    name: Update ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update {{ matrix.version }}
        run: ./update.sh '{{ matrix.version }}'
      # TODO build, test?, commit+push
